/**
 * Environment-based plan adjuster for OpenClaw installation.
 *
 * Adjusts the generated installation plan based on environment specifics:
 * - macOS specific steps (Homebrew, Xcode CLT, Apple Silicon)
 * - Linux distribution differences (apt vs yum, snap availability)
 * - Windows/WSL handling (detect WSL, adjust commands accordingly)
 *
 * Works as a post-processing stage after the base plan is generated by
 * `planner.ts`, enriching it with platform-aware steps and adjustments.
 *
 * @module installers/openclaw/env-plan-adjuster
 */

import type { EnvironmentInfo, InstallPlan, InstallStep } from '@aiinstaller/shared';

import type { DetectResult } from './detect.js';
import { QUICK_TIMEOUT, INSTALL_TIMEOUT, HEAVY_INSTALL_TIMEOUT } from './steps.js';
import type { Risk } from './planner.js';

// ============================================================================
// Types
// ============================================================================

/** Describes the detected Linux distribution family. */
export type LinuxDistro = 'debian' | 'redhat' | 'arch' | 'alpine' | 'unknown';

/** Describes the detected macOS chip architecture. */
export type MacChip = 'apple-silicon' | 'intel';

/** Result of platform-specific environment analysis. */
export interface PlatformAnalysis {
  /** The platform being analyzed */
  platform: 'darwin' | 'linux' | 'win32';
  /** Whether WSL is detected (Windows only) */
  isWSL: boolean;
  /** Linux distribution family (Linux only) */
  linuxDistro: LinuxDistro;
  /** macOS chip type (macOS only) */
  macChip: MacChip;
  /** Whether Homebrew is available (macOS) */
  hasHomebrew: boolean;
  /** Whether apt is available (Linux) */
  hasApt: boolean;
  /** Whether the system has a Node version manager (nvm, fnm, etc.) */
  hasNodeVersionManager: boolean;
}

// ============================================================================
// Platform analysis
// ============================================================================

/**
 * Detect the Linux distribution family based on available package managers.
 *
 * @param env - Environment info from the agent
 * @returns The detected Linux distribution family
 */
export function detectLinuxDistro(env: EnvironmentInfo): LinuxDistro {
  if (env.packageManagers.apt) return 'debian';
  // No yum/dnf/pacman/apk in the schema, so we infer from hints
  return 'unknown';
}

/**
 * Detect the macOS chip architecture.
 *
 * @param env - Environment info from the agent
 * @returns 'apple-silicon' for arm64, 'intel' otherwise
 */
export function detectMacChip(env: EnvironmentInfo): MacChip {
  return env.os.arch === 'arm64' ? 'apple-silicon' : 'intel';
}

/**
 * Detect whether the environment is running under WSL.
 *
 * Heuristic: platform is 'win32' but shell is bash/zsh (typical of WSL),
 * or platform is 'linux' and OS version string contains "microsoft" (WSL kernel).
 *
 * @param env - Environment info from the agent
 * @returns true if WSL is detected
 */
export function detectWSL(env: EnvironmentInfo): boolean {
  // WSL typically reports as linux with "microsoft" in the kernel version
  if (
    env.os.platform === 'linux' &&
    env.os.version.toLowerCase().includes('microsoft')
  ) {
    return true;
  }
  // Alternative: win32 platform with a Unix-like shell
  if (
    env.os.platform === 'win32' &&
    (env.shell.type === 'bash' || env.shell.type === 'zsh')
  ) {
    return true;
  }
  return false;
}

/**
 * Perform a comprehensive platform analysis of the environment.
 *
 * @param env - Environment info from the agent
 * @returns A PlatformAnalysis describing the target environment
 */
export function analyzePlatform(env: EnvironmentInfo): PlatformAnalysis {
  return {
    platform: env.os.platform,
    isWSL: detectWSL(env),
    linuxDistro: env.os.platform === 'linux' ? detectLinuxDistro(env) : 'unknown',
    macChip: env.os.platform === 'darwin' ? detectMacChip(env) : 'intel',
    hasHomebrew: !!env.packageManagers.brew,
    hasApt: !!env.packageManagers.apt,
    hasNodeVersionManager: false, // detected by Node version manager presence in path/config
  };
}

// ============================================================================
// macOS-specific adjustments
// ============================================================================

/**
 * Generate macOS-specific steps to prepend to the installation plan.
 *
 * - If Node.js check failed and Homebrew is available, add a Homebrew install step.
 * - If on Apple Silicon, adjust Node install commands for compatibility.
 *
 * @param detectResult - Environment detection result
 * @param env - Raw environment info
 * @param analysis - Platform analysis
 * @returns Array of macOS-specific steps to prepend
 */
export function getMacOSSteps(
  detectResult: DetectResult,
  env: EnvironmentInfo,
  analysis: PlatformAnalysis,
): InstallStep[] {
  const steps: InstallStep[] = [];

  // If Node.js is not installed and Homebrew is available, offer to install via brew
  if (!detectResult.checks.nodeVersion.passed && analysis.hasHomebrew) {
    steps.push({
      id: 'install-node-brew',
      description: '通过 Homebrew 安装 Node.js 22',
      command: 'brew install node@22',
      timeout: HEAVY_INSTALL_TIMEOUT,
      canRollback: true,
      onError: 'fallback',
    });

    // On Apple Silicon, ensure Homebrew paths are correct
    if (analysis.macChip === 'apple-silicon') {
      steps.push({
        id: 'setup-brew-path-arm64',
        description: '配置 Apple Silicon Homebrew 路径',
        command: 'eval "$(/opt/homebrew/bin/brew shellenv)"',
        timeout: QUICK_TIMEOUT,
        canRollback: false,
        onError: 'skip',
      });
    }
  }

  // If pnpm is not installed but Homebrew is available, offer corepack alternative
  if (!detectResult.checks.pnpm.passed && analysis.hasHomebrew) {
    steps.push({
      id: 'enable-corepack-macos',
      description: '通过 corepack 启用 pnpm',
      command: 'corepack enable && corepack prepare pnpm@latest --activate',
      timeout: INSTALL_TIMEOUT,
      canRollback: true,
      onError: 'fallback',
    });
  }

  return steps;
}

/**
 * Get macOS-specific risks.
 *
 * @param analysis - Platform analysis
 * @returns Array of macOS-specific risks
 */
export function getMacOSRisks(analysis: PlatformAnalysis): Risk[] {
  const risks: Risk[] = [];

  if (analysis.macChip === 'apple-silicon') {
    risks.push({
      level: 'low',
      description: 'Apple Silicon (arm64) detected. Some native modules may need Rosetta 2.',
    });
  }

  return risks;
}

// ============================================================================
// Linux-specific adjustments
// ============================================================================

/**
 * Generate Linux-specific steps to prepend to the installation plan.
 *
 * - For Debian-based distros, use apt to install Node.js if missing.
 * - Add build-essential installation if native modules may be needed.
 *
 * @param detectResult - Environment detection result
 * @param env - Raw environment info
 * @param analysis - Platform analysis
 * @returns Array of Linux-specific steps to prepend
 */
export function getLinuxSteps(
  detectResult: DetectResult,
  env: EnvironmentInfo,
  analysis: PlatformAnalysis,
): InstallStep[] {
  const steps: InstallStep[] = [];
  const sudoPrefix = env.permissions.hasSudo ? 'sudo ' : '';

  // If Node.js is not installed and apt is available, install via apt
  if (!detectResult.checks.nodeVersion.passed && analysis.hasApt) {
    steps.push({
      id: 'install-node-apt',
      description: '通过 apt 安装 Node.js 22 (NodeSource)',
      command: `${sudoPrefix}apt-get update && curl -fsSL https://deb.nodesource.com/setup_22.x | ${sudoPrefix}bash - && ${sudoPrefix}apt-get install -y nodejs`,
      timeout: HEAVY_INSTALL_TIMEOUT,
      canRollback: true,
      onError: 'fallback',
    });
  }

  // Install build-essential for native modules (Debian-based)
  if (analysis.linuxDistro === 'debian' && analysis.hasApt) {
    steps.push({
      id: 'install-build-essential',
      description: '安装编译工具 (build-essential)',
      command: `${sudoPrefix}apt-get install -y build-essential`,
      timeout: INSTALL_TIMEOUT,
      canRollback: true,
      onError: 'skip',
    });
  }

  return steps;
}

/**
 * Get Linux-specific risks.
 *
 * @param analysis - Platform analysis
 * @param env - Raw environment info
 * @returns Array of Linux-specific risks
 */
export function getLinuxRisks(analysis: PlatformAnalysis, env: EnvironmentInfo): Risk[] {
  const risks: Risk[] = [];

  if (analysis.linuxDistro === 'unknown') {
    risks.push({
      level: 'medium',
      description: 'Unknown Linux distribution. Package install commands may need manual adjustment.',
    });
  }

  if (!env.permissions.hasSudo && env.permissions.canWriteTo.length === 0) {
    risks.push({
      level: 'high',
      description: 'No sudo access and no writable directories on Linux. Global installs will fail.',
    });
  }

  return risks;
}

// ============================================================================
// Windows/WSL-specific adjustments
// ============================================================================

/**
 * Generate Windows/WSL-specific steps to prepend to the installation plan.
 *
 * - On WSL, ensure interoperability is configured correctly.
 * - On native Windows, adjust commands for PowerShell compatibility.
 *
 * @param detectResult - Environment detection result
 * @param env - Raw environment info
 * @param analysis - Platform analysis
 * @returns Array of Windows/WSL-specific steps to prepend
 */
export function getWindowsSteps(
  detectResult: DetectResult,
  env: EnvironmentInfo,
  analysis: PlatformAnalysis,
): InstallStep[] {
  const steps: InstallStep[] = [];

  if (analysis.isWSL) {
    // WSL: verify WSL interop is working
    steps.push({
      id: 'verify-wsl',
      description: '验证 WSL 环境',
      command: 'wsl --status || echo "WSL environment detected"',
      timeout: QUICK_TIMEOUT,
      canRollback: false,
      onError: 'skip',
    });
  }

  // On native Windows (not WSL), if Node.js is missing, use winget or choco
  if (
    env.os.platform === 'win32' &&
    !analysis.isWSL &&
    !detectResult.checks.nodeVersion.passed
  ) {
    steps.push({
      id: 'install-node-windows',
      description: '通过 winget 安装 Node.js 22',
      command: 'winget install OpenJS.NodeJS.LTS --version 22',
      timeout: HEAVY_INSTALL_TIMEOUT,
      canRollback: true,
      onError: 'fallback',
    });
  }

  return steps;
}

/**
 * Get Windows/WSL-specific risks.
 *
 * @param analysis - Platform analysis
 * @returns Array of Windows/WSL-specific risks
 */
export function getWindowsRisks(analysis: PlatformAnalysis): Risk[] {
  const risks: Risk[] = [];

  if (analysis.isWSL) {
    risks.push({
      level: 'low',
      description: 'WSL detected. Installation will proceed in Linux mode within WSL.',
    });
  } else {
    risks.push({
      level: 'medium',
      description: 'Native Windows detected. Some POSIX commands may not work. Consider using WSL.',
    });
  }

  return risks;
}

// ============================================================================
// Main adjuster
// ============================================================================

/**
 * Adjust an installation plan based on detailed environment analysis.
 *
 * This function is the main entry point for environment-based plan adjustment.
 * It analyzes the platform, generates platform-specific steps and risks,
 * and merges them into the existing plan.
 *
 * Platform-specific steps are inserted after the 'check-node' step (or at
 * position 0 if check-node is not found), ensuring prerequisite installations
 * happen before the main OpenClaw install steps.
 *
 * @param plan - The base installation plan from generatePlan()
 * @param detectResult - Environment detection result
 * @param env - Raw environment info from the agent
 * @returns Adjusted plan with platform-specific steps and risks added
 */
export function adjustPlanForEnvironment(
  plan: InstallPlan,
  detectResult: DetectResult,
  env: EnvironmentInfo,
): InstallPlan {
  const analysis = analyzePlatform(env);
  let platformSteps: InstallStep[] = [];
  let platformRisks: Risk[] = [];

  switch (analysis.platform) {
    case 'darwin':
      platformSteps = getMacOSSteps(detectResult, env, analysis);
      platformRisks = getMacOSRisks(analysis);
      break;
    case 'linux':
      if (analysis.isWSL) {
        // WSL is treated as Windows-like but with Linux commands
        platformSteps = getWindowsSteps(detectResult, env, analysis);
        platformRisks = getWindowsRisks(analysis);
      } else {
        platformSteps = getLinuxSteps(detectResult, env, analysis);
        platformRisks = getLinuxRisks(analysis, env);
      }
      break;
    case 'win32':
      platformSteps = getWindowsSteps(detectResult, env, analysis);
      platformRisks = getWindowsRisks(analysis);
      break;
  }

  // Merge platform-specific steps: insert after 'check-node' step
  const adjustedSteps = [...plan.steps];
  if (platformSteps.length > 0) {
    const checkNodeIndex = adjustedSteps.findIndex((s) => s.id === 'check-node');
    const insertAt = checkNodeIndex >= 0 ? checkNodeIndex + 1 : 0;
    adjustedSteps.splice(insertAt, 0, ...platformSteps);
  }

  // Merge platform-specific risks (avoid duplicates by description)
  const existingDescriptions = new Set(plan.risks.map((r) => r.description));
  const newRisks = platformRisks.filter((r) => !existingDescriptions.has(r.description));
  const adjustedRisks = [...plan.risks, ...newRisks];

  // Recalculate estimated time with the new steps
  const estimatedTime = adjustedSteps.reduce(
    (total, step) => total + step.timeout * 0.3,
    0,
  );

  return {
    steps: adjustedSteps,
    estimatedTime,
    risks: adjustedRisks,
  };
}
